name: Format Check Reuse

# Run on all push and pull requests
on:
  push:
  pull_request:

jobs:
  format-check:
    name: Run format check
    uses: ArielSAdamsNASA/cFS-JSF-Rules/.github/workflows/format-check.yml@Rule1
