name: Static Analysis

# Run on all push and pull requests
on:
  push:
  pull_request:
  workflow_call:
    inputs:
      module:
        description: 'GitHub Module'
        type: string
        default: 'bundle'
      cppcheck-code:
        description: 'Cppcheck Code'
        type: string
        default: ''

jobs:
  #Checks for duplicate actions. Skips push actions if there is a matching or duplicate pull-request action. 
  check-for-duplicates:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
        should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  static-analysis:
    #Continue if check-for-duplicates found no duplicates. Always runs for pull-requests.
    needs: check-for-duplicates
    if: ${{ needs.check-for-duplicates.outputs.should_skip != 'true' }}
    name: Run cppcheck
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        cppcheck: bundle, ${{ events.github.inputs.module }}

    steps:      
      - name: Install cppcheck
        run: sudo apt-get install cppcheck -y

        # Checks out a copy of the cfs bundle
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Run bundle cppcheck
        run: cppcheck --force --inline-suppr --quiet . 2> bundle_cppcheck_err.txt

        # Run strict static analysis for embedded portions of cfe, osal, and psp
      - name: Strict cppcheck
        if: ${{ github.event.inputs.module !='bundle' }}
        run: |
          ${{ github.event.inputs.cppcheck-code }}

      - name: Archive Static Analysis Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.cppcheck}}-cppcheck-err
          path: ./*cppcheck_err.txt

      - name: Check for errors
        run: |
          if [[ -s ${{matrix.cppcheck}}_cppcheck_err.txt ]];
          then
            cat ${{matrix.cppcheck}}_cppcheck_err.txt
            exit -1
          fi
